### ISSUE TITLE
How to put image filename, or a "small title" under each the thumbnail

### ISSUE THREAD

**Issue by J4bber** [shred/phpminigallery#5]
I would like to put either the filename of the picture under the thumbnail OR have something like "th_filename.txt" for a short thumbnail description.   

I have poked around in the PHP but having found where I can grab that and display it...

think this is something you could add??

**Comment by shred** [comment]
To add the filename or a capture under the thumbnail, the `index.php` file around line 197 needs to be changed. For example, this change should show the image file name below the thumbnail (untested):

```php
    $page .= sprintf(
      '<td><a href="index.php?pic=%s"><img class="thumbimg" src="index.php?thumb=%s" alt="#%s" border="0" /></a><br>%s</td>',
      htmlspecialchars($file),
      htmlspecialchars($file),
      htmlspecialchars($key+1),
      htmlspecialchars($file)
    );
```

This project is very old, and I stopped writing PHP many years ago now, so I won't add it. :smiley: But maybe someone else will send a pull request.

**Comment by J4bber** [comment]
Haha, yeah I stopped PHP at least 10+ years.  Forgotten most of it.   I'll look at your suggestion and poke around some more...   Thanks for the help.
